### ISSUE TITLE
add more projects

### ISSUE THREAD

**Issue by ShreeyashGarde** [AnanyaDas162/Code-Collection-Hacktoberfest2022#384]
hey , can i add more web dev projects?

**Comment by AnanyaDas162** [comment]
Yeah definitely, you can add.....And again thanks to you sir!!

**Comment by ShreeyashGarde** [comment]
ok will do , thanks

**Comment by ShreeyashGarde** [comment]
Added the project pls do the needful , thanks.

**Comment by AnanyaDas162** [comment]
Yeah, your project is merged. And thanks for collaborating with me!!!

**Comment by ShreeyashGarde** [comment]
yes , thank you very much.
